/* tslint:disable */
/* eslint-disable */
/**
 * CineReserve
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { BookingRecord } from './BookingRecord';
import {
    BookingRecordFromJSON,
    BookingRecordFromJSONTyped,
    BookingRecordToJSON,
    BookingRecordToJSONTyped,
} from './BookingRecord';

/**
 * 
 * @export
 * @interface BookingRecordPagedResponse
 */
export interface BookingRecordPagedResponse {
    /**
     * 
     * @type {number}
     * @memberof BookingRecordPagedResponse
     */
    page: number;
    /**
     * 
     * @type {number}
     * @memberof BookingRecordPagedResponse
     */
    pageSize: number;
    /**
     * 
     * @type {number}
     * @memberof BookingRecordPagedResponse
     */
    totalCount: number;
    /**
     * 
     * @type {Array<BookingRecord>}
     * @memberof BookingRecordPagedResponse
     */
    data: Array<BookingRecord>;
}

/**
 * Check if a given object implements the BookingRecordPagedResponse interface.
 */
export function instanceOfBookingRecordPagedResponse(value: object): value is BookingRecordPagedResponse {
    if (!('page' in value) || value['page'] === undefined) return false;
    if (!('pageSize' in value) || value['pageSize'] === undefined) return false;
    if (!('totalCount' in value) || value['totalCount'] === undefined) return false;
    if (!('data' in value) || value['data'] === undefined) return false;
    return true;
}

export function BookingRecordPagedResponseFromJSON(json: any): BookingRecordPagedResponse {
    return BookingRecordPagedResponseFromJSONTyped(json, false);
}

export function BookingRecordPagedResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): BookingRecordPagedResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'page': json['page'],
        'pageSize': json['pageSize'],
        'totalCount': json['totalCount'],
        'data': ((json['data'] as Array<any>).map(BookingRecordFromJSON)),
    };
}

export function BookingRecordPagedResponseToJSON(json: any): BookingRecordPagedResponse {
    return BookingRecordPagedResponseToJSONTyped(json, false);
}

export function BookingRecordPagedResponseToJSONTyped(value?: BookingRecordPagedResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'page': value['page'],
        'pageSize': value['pageSize'],
        'totalCount': value['totalCount'],
        'data': ((value['data'] as Array<any>).map(BookingRecordToJSON)),
    };
}

