/* tslint:disable */
/* eslint-disable */
/**
 * CineReserve
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface BookingRecord
 */
export interface BookingRecord {
    /**
     * 
     * @type {string}
     * @memberof BookingRecord
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof BookingRecord
     */
    userId: string;
    /**
     * 
     * @type {string}
     * @memberof BookingRecord
     */
    screeningId: string;
}

/**
 * Check if a given object implements the BookingRecord interface.
 */
export function instanceOfBookingRecord(value: object): value is BookingRecord {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('userId' in value) || value['userId'] === undefined) return false;
    if (!('screeningId' in value) || value['screeningId'] === undefined) return false;
    return true;
}

export function BookingRecordFromJSON(json: any): BookingRecord {
    return BookingRecordFromJSONTyped(json, false);
}

export function BookingRecordFromJSONTyped(json: any, ignoreDiscriminator: boolean): BookingRecord {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'userId': json['userId'],
        'screeningId': json['screeningId'],
    };
}

export function BookingRecordToJSON(json: any): BookingRecord {
    return BookingRecordToJSONTyped(json, false);
}

export function BookingRecordToJSONTyped(value?: BookingRecord | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'userId': value['userId'],
        'screeningId': value['screeningId'],
    };
}

