/* tslint:disable */
/* eslint-disable */
/**
 * CineReserve
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface BookingUpdateRecord
 */
export interface BookingUpdateRecord {
    /**
     * 
     * @type {string}
     * @memberof BookingUpdateRecord
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof BookingUpdateRecord
     */
    userId?: string | null;
    /**
     * 
     * @type {string}
     * @memberof BookingUpdateRecord
     */
    screeningId?: string | null;
}

/**
 * Check if a given object implements the BookingUpdateRecord interface.
 */
export function instanceOfBookingUpdateRecord(value: object): value is BookingUpdateRecord {
    if (!('id' in value) || value['id'] === undefined) return false;
    return true;
}

export function BookingUpdateRecordFromJSON(json: any): BookingUpdateRecord {
    return BookingUpdateRecordFromJSONTyped(json, false);
}

export function BookingUpdateRecordFromJSONTyped(json: any, ignoreDiscriminator: boolean): BookingUpdateRecord {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'userId': json['userId'] == null ? undefined : json['userId'],
        'screeningId': json['screeningId'] == null ? undefined : json['screeningId'],
    };
}

export function BookingUpdateRecordToJSON(json: any): BookingUpdateRecord {
    return BookingUpdateRecordToJSONTyped(json, false);
}

export function BookingUpdateRecordToJSONTyped(value?: BookingUpdateRecord | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'userId': value['userId'],
        'screeningId': value['screeningId'],
    };
}

