/* tslint:disable */
/* eslint-disable */
/**
 * CineReserve
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { BookingRecordPagedResponse } from './BookingRecordPagedResponse';
import {
    BookingRecordPagedResponseFromJSON,
    BookingRecordPagedResponseFromJSONTyped,
    BookingRecordPagedResponseToJSON,
    BookingRecordPagedResponseToJSONTyped,
} from './BookingRecordPagedResponse';
import type { ErrorMessage } from './ErrorMessage';
import {
    ErrorMessageFromJSON,
    ErrorMessageFromJSONTyped,
    ErrorMessageToJSON,
    ErrorMessageToJSONTyped,
} from './ErrorMessage';

/**
 * 
 * @export
 * @interface BookingRecordPagedResponseRequestResponse
 */
export interface BookingRecordPagedResponseRequestResponse {
    /**
     * 
     * @type {BookingRecordPagedResponse}
     * @memberof BookingRecordPagedResponseRequestResponse
     */
    readonly response?: BookingRecordPagedResponse | null;
    /**
     * 
     * @type {ErrorMessage}
     * @memberof BookingRecordPagedResponseRequestResponse
     */
    readonly errorMessage?: ErrorMessage | null;
}

/**
 * Check if a given object implements the BookingRecordPagedResponseRequestResponse interface.
 */
export function instanceOfBookingRecordPagedResponseRequestResponse(value: object): value is BookingRecordPagedResponseRequestResponse {
    return true;
}

export function BookingRecordPagedResponseRequestResponseFromJSON(json: any): BookingRecordPagedResponseRequestResponse {
    return BookingRecordPagedResponseRequestResponseFromJSONTyped(json, false);
}

export function BookingRecordPagedResponseRequestResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): BookingRecordPagedResponseRequestResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'response': json['response'] == null ? undefined : BookingRecordPagedResponseFromJSON(json['response']),
        'errorMessage': json['errorMessage'] == null ? undefined : ErrorMessageFromJSON(json['errorMessage']),
    };
}

export function BookingRecordPagedResponseRequestResponseToJSON(json: any): BookingRecordPagedResponseRequestResponse {
    return BookingRecordPagedResponseRequestResponseToJSONTyped(json, false);
}

export function BookingRecordPagedResponseRequestResponseToJSONTyped(value?: Omit<BookingRecordPagedResponseRequestResponse, 'response'|'errorMessage'> | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
    };
}

