/* tslint:disable */
/* eslint-disable */
/**
 * CineReserve
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ErrorMessage } from './ErrorMessage';
import {
    ErrorMessageFromJSON,
    ErrorMessageFromJSONTyped,
    ErrorMessageToJSON,
    ErrorMessageToJSONTyped,
} from './ErrorMessage';
import type { FeedbackRecord } from './FeedbackRecord';
import {
    FeedbackRecordFromJSON,
    FeedbackRecordFromJSONTyped,
    FeedbackRecordToJSON,
    FeedbackRecordToJSONTyped,
} from './FeedbackRecord';

/**
 * 
 * @export
 * @interface FeedbackRecordRequestResponse
 */
export interface FeedbackRecordRequestResponse {
    /**
     * 
     * @type {FeedbackRecord}
     * @memberof FeedbackRecordRequestResponse
     */
    readonly response?: FeedbackRecord | null;
    /**
     * 
     * @type {ErrorMessage}
     * @memberof FeedbackRecordRequestResponse
     */
    readonly errorMessage?: ErrorMessage | null;
}

/**
 * Check if a given object implements the FeedbackRecordRequestResponse interface.
 */
export function instanceOfFeedbackRecordRequestResponse(value: object): value is FeedbackRecordRequestResponse {
    return true;
}

export function FeedbackRecordRequestResponseFromJSON(json: any): FeedbackRecordRequestResponse {
    return FeedbackRecordRequestResponseFromJSONTyped(json, false);
}

export function FeedbackRecordRequestResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): FeedbackRecordRequestResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'response': json['response'] == null ? undefined : FeedbackRecordFromJSON(json['response']),
        'errorMessage': json['errorMessage'] == null ? undefined : ErrorMessageFromJSON(json['errorMessage']),
    };
}

export function FeedbackRecordRequestResponseToJSON(json: any): FeedbackRecordRequestResponse {
    return FeedbackRecordRequestResponseToJSONTyped(json, false);
}

export function FeedbackRecordRequestResponseToJSONTyped(value?: Omit<FeedbackRecordRequestResponse, 'response'|'errorMessage'> | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
    };
}

