/* tslint:disable */
/* eslint-disable */
/**
 * CineReserve
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ErrorMessage } from './ErrorMessage';
import {
    ErrorMessageFromJSON,
    ErrorMessageFromJSONTyped,
    ErrorMessageToJSON,
    ErrorMessageToJSONTyped,
} from './ErrorMessage';
import type { FeedbackRecordPagedResponse } from './FeedbackRecordPagedResponse';
import {
    FeedbackRecordPagedResponseFromJSON,
    FeedbackRecordPagedResponseFromJSONTyped,
    FeedbackRecordPagedResponseToJSON,
    FeedbackRecordPagedResponseToJSONTyped,
} from './FeedbackRecordPagedResponse';

/**
 * 
 * @export
 * @interface FeedbackRecordPagedResponseRequestResponse
 */
export interface FeedbackRecordPagedResponseRequestResponse {
    /**
     * 
     * @type {FeedbackRecordPagedResponse}
     * @memberof FeedbackRecordPagedResponseRequestResponse
     */
    readonly response?: FeedbackRecordPagedResponse | null;
    /**
     * 
     * @type {ErrorMessage}
     * @memberof FeedbackRecordPagedResponseRequestResponse
     */
    readonly errorMessage?: ErrorMessage | null;
}

/**
 * Check if a given object implements the FeedbackRecordPagedResponseRequestResponse interface.
 */
export function instanceOfFeedbackRecordPagedResponseRequestResponse(value: object): value is FeedbackRecordPagedResponseRequestResponse {
    return true;
}

export function FeedbackRecordPagedResponseRequestResponseFromJSON(json: any): FeedbackRecordPagedResponseRequestResponse {
    return FeedbackRecordPagedResponseRequestResponseFromJSONTyped(json, false);
}

export function FeedbackRecordPagedResponseRequestResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): FeedbackRecordPagedResponseRequestResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'response': json['response'] == null ? undefined : FeedbackRecordPagedResponseFromJSON(json['response']),
        'errorMessage': json['errorMessage'] == null ? undefined : ErrorMessageFromJSON(json['errorMessage']),
    };
}

export function FeedbackRecordPagedResponseRequestResponseToJSON(json: any): FeedbackRecordPagedResponseRequestResponse {
    return FeedbackRecordPagedResponseRequestResponseToJSONTyped(json, false);
}

export function FeedbackRecordPagedResponseRequestResponseToJSONTyped(value?: Omit<FeedbackRecordPagedResponseRequestResponse, 'response'|'errorMessage'> | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
    };
}

