/* tslint:disable */
/* eslint-disable */
/**
 * CineReserve
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface FeedbackRecord
 */
export interface FeedbackRecord {
    /**
     * 
     * @type {string}
     * @memberof FeedbackRecord
     */
    id: string;
    /**
     * 
     * @type {number}
     * @memberof FeedbackRecord
     */
    rating: number;
    /**
     * 
     * @type {string}
     * @memberof FeedbackRecord
     */
    comment: string;
    /**
     * 
     * @type {boolean}
     * @memberof FeedbackRecord
     */
    wouldRecommend?: boolean | null;
    /**
     * 
     * @type {string}
     * @memberof FeedbackRecord
     */
    userId: string;
    /**
     * 
     * @type {string}
     * @memberof FeedbackRecord
     */
    movieId: string;
}

/**
 * Check if a given object implements the FeedbackRecord interface.
 */
export function instanceOfFeedbackRecord(value: object): value is FeedbackRecord {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('rating' in value) || value['rating'] === undefined) return false;
    if (!('comment' in value) || value['comment'] === undefined) return false;
    if (!('userId' in value) || value['userId'] === undefined) return false;
    if (!('movieId' in value) || value['movieId'] === undefined) return false;
    return true;
}

export function FeedbackRecordFromJSON(json: any): FeedbackRecord {
    return FeedbackRecordFromJSONTyped(json, false);
}

export function FeedbackRecordFromJSONTyped(json: any, ignoreDiscriminator: boolean): FeedbackRecord {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'rating': json['rating'],
        'comment': json['comment'],
        'wouldRecommend': json['wouldRecommend'] == null ? undefined : json['wouldRecommend'],
        'userId': json['userId'],
        'movieId': json['movieId'],
    };
}

export function FeedbackRecordToJSON(json: any): FeedbackRecord {
    return FeedbackRecordToJSONTyped(json, false);
}

export function FeedbackRecordToJSONTyped(value?: FeedbackRecord | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'rating': value['rating'],
        'comment': value['comment'],
        'wouldRecommend': value['wouldRecommend'],
        'userId': value['userId'],
        'movieId': value['movieId'],
    };
}

