/* tslint:disable */
/* eslint-disable */
/**
 * CineReserve
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface FeedbackUpdateRecord
 */
export interface FeedbackUpdateRecord {
    /**
     * 
     * @type {string}
     * @memberof FeedbackUpdateRecord
     */
    id: string;
    /**
     * 
     * @type {number}
     * @memberof FeedbackUpdateRecord
     */
    rating?: number | null;
    /**
     * 
     * @type {string}
     * @memberof FeedbackUpdateRecord
     */
    comment?: string | null;
    /**
     * 
     * @type {boolean}
     * @memberof FeedbackUpdateRecord
     */
    wouldRecommend?: boolean | null;
    /**
     * 
     * @type {string}
     * @memberof FeedbackUpdateRecord
     */
    userId?: string | null;
    /**
     * 
     * @type {string}
     * @memberof FeedbackUpdateRecord
     */
    movieId?: string | null;
}

/**
 * Check if a given object implements the FeedbackUpdateRecord interface.
 */
export function instanceOfFeedbackUpdateRecord(value: object): value is FeedbackUpdateRecord {
    if (!('id' in value) || value['id'] === undefined) return false;
    return true;
}

export function FeedbackUpdateRecordFromJSON(json: any): FeedbackUpdateRecord {
    return FeedbackUpdateRecordFromJSONTyped(json, false);
}

export function FeedbackUpdateRecordFromJSONTyped(json: any, ignoreDiscriminator: boolean): FeedbackUpdateRecord {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'rating': json['rating'] == null ? undefined : json['rating'],
        'comment': json['comment'] == null ? undefined : json['comment'],
        'wouldRecommend': json['wouldRecommend'] == null ? undefined : json['wouldRecommend'],
        'userId': json['userId'] == null ? undefined : json['userId'],
        'movieId': json['movieId'] == null ? undefined : json['movieId'],
    };
}

export function FeedbackUpdateRecordToJSON(json: any): FeedbackUpdateRecord {
    return FeedbackUpdateRecordToJSONTyped(json, false);
}

export function FeedbackUpdateRecordToJSONTyped(value?: FeedbackUpdateRecord | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'rating': value['rating'],
        'comment': value['comment'],
        'wouldRecommend': value['wouldRecommend'],
        'userId': value['userId'],
        'movieId': value['movieId'],
    };
}

