/* tslint:disable */
/* eslint-disable */
/**
 * CineReserve
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const FoodEnum = {
    NoFood: 'NoFood',
    Nachos: 'Nachos',
    Popcorn: 'Popcorn',
    NachosAndPopcorn: 'NachosAndPopcorn'
} as const;
export type FoodEnum = typeof FoodEnum[keyof typeof FoodEnum];


export function instanceOfFoodEnum(value: any): boolean {
    for (const key in FoodEnum) {
        if (Object.prototype.hasOwnProperty.call(FoodEnum, key)) {
            if (FoodEnum[key as keyof typeof FoodEnum] === value) {
                return true;
            }
        }
    }
    return false;
}

export function FoodEnumFromJSON(json: any): FoodEnum {
    return FoodEnumFromJSONTyped(json, false);
}

export function FoodEnumFromJSONTyped(json: any, ignoreDiscriminator: boolean): FoodEnum {
    return json as FoodEnum;
}

export function FoodEnumToJSON(value?: FoodEnum | null): any {
    return value as any;
}

export function FoodEnumToJSONTyped(value: any, ignoreDiscriminator: boolean): FoodEnum {
    return value as FoodEnum;
}

