/* tslint:disable */
/* eslint-disable */
/**
 * CineReserve
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const GenreEnum = {
    Action: 'Action',
    Adventure: 'Adventure',
    Comedy: 'Comedy',
    Drama: 'Drama',
    Horror: 'Horror',
    SciFi: 'SciFi',
    Romance: 'Romance',
    Thriller: 'Thriller',
    Animation: 'Animation',
    Documentary: 'Documentary',
    Fantasy: 'Fantasy'
} as const;
export type GenreEnum = typeof GenreEnum[keyof typeof GenreEnum];


export function instanceOfGenreEnum(value: any): boolean {
    for (const key in GenreEnum) {
        if (Object.prototype.hasOwnProperty.call(GenreEnum, key)) {
            if (GenreEnum[key as keyof typeof GenreEnum] === value) {
                return true;
            }
        }
    }
    return false;
}

export function GenreEnumFromJSON(json: any): GenreEnum {
    return GenreEnumFromJSONTyped(json, false);
}

export function GenreEnumFromJSONTyped(json: any, ignoreDiscriminator: boolean): GenreEnum {
    return json as GenreEnum;
}

export function GenreEnumToJSON(value?: GenreEnum | null): any {
    return value as any;
}

export function GenreEnumToJSONTyped(value: any, ignoreDiscriminator: boolean): GenreEnum {
    return value as GenreEnum;
}

