/* tslint:disable */
/* eslint-disable */
/**
 * CineReserve
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { HallRecord } from './HallRecord';
import {
    HallRecordFromJSON,
    HallRecordFromJSONTyped,
    HallRecordToJSON,
    HallRecordToJSONTyped,
} from './HallRecord';
import type { ErrorMessage } from './ErrorMessage';
import {
    ErrorMessageFromJSON,
    ErrorMessageFromJSONTyped,
    ErrorMessageToJSON,
    ErrorMessageToJSONTyped,
} from './ErrorMessage';

/**
 * 
 * @export
 * @interface HallRecordRequestResponse
 */
export interface HallRecordRequestResponse {
    /**
     * 
     * @type {HallRecord}
     * @memberof HallRecordRequestResponse
     */
    readonly response?: HallRecord | null;
    /**
     * 
     * @type {ErrorMessage}
     * @memberof HallRecordRequestResponse
     */
    readonly errorMessage?: ErrorMessage | null;
}

/**
 * Check if a given object implements the HallRecordRequestResponse interface.
 */
export function instanceOfHallRecordRequestResponse(value: object): value is HallRecordRequestResponse {
    return true;
}

export function HallRecordRequestResponseFromJSON(json: any): HallRecordRequestResponse {
    return HallRecordRequestResponseFromJSONTyped(json, false);
}

export function HallRecordRequestResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): HallRecordRequestResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'response': json['response'] == null ? undefined : HallRecordFromJSON(json['response']),
        'errorMessage': json['errorMessage'] == null ? undefined : ErrorMessageFromJSON(json['errorMessage']),
    };
}

export function HallRecordRequestResponseToJSON(json: any): HallRecordRequestResponse {
    return HallRecordRequestResponseToJSONTyped(json, false);
}

export function HallRecordRequestResponseToJSONTyped(value?: Omit<HallRecordRequestResponse, 'response'|'errorMessage'> | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
    };
}

