/* tslint:disable */
/* eslint-disable */
/**
 * CineReserve
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface HallRecord
 */
export interface HallRecord {
    /**
     * 
     * @type {string}
     * @memberof HallRecord
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof HallRecord
     */
    name: string;
    /**
     * 
     * @type {number}
     * @memberof HallRecord
     */
    capacity: number;
}

/**
 * Check if a given object implements the HallRecord interface.
 */
export function instanceOfHallRecord(value: object): value is HallRecord {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('capacity' in value) || value['capacity'] === undefined) return false;
    return true;
}

export function HallRecordFromJSON(json: any): HallRecord {
    return HallRecordFromJSONTyped(json, false);
}

export function HallRecordFromJSONTyped(json: any, ignoreDiscriminator: boolean): HallRecord {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'name': json['name'],
        'capacity': json['capacity'],
    };
}

export function HallRecordToJSON(json: any): HallRecord {
    return HallRecordToJSONTyped(json, false);
}

export function HallRecordToJSONTyped(value?: HallRecord | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
        'capacity': value['capacity'],
    };
}

