/* tslint:disable */
/* eslint-disable */
/**
 * CineReserve
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { GenreEnum } from './GenreEnum';
import {
    GenreEnumFromJSON,
    GenreEnumFromJSONTyped,
    GenreEnumToJSON,
    GenreEnumToJSONTyped,
} from './GenreEnum';

/**
 * 
 * @export
 * @interface MovieAddRecord
 */
export interface MovieAddRecord {
    /**
     * 
     * @type {string}
     * @memberof MovieAddRecord
     */
    title: string;
    /**
     * 
     * @type {string}
     * @memberof MovieAddRecord
     */
    description: string;
    /**
     * 
     * @type {number}
     * @memberof MovieAddRecord
     */
    duration: number;
    /**
     * 
     * @type {GenreEnum}
     * @memberof MovieAddRecord
     */
    genre: GenreEnum;
}



/**
 * Check if a given object implements the MovieAddRecord interface.
 */
export function instanceOfMovieAddRecord(value: object): value is MovieAddRecord {
    if (!('title' in value) || value['title'] === undefined) return false;
    if (!('description' in value) || value['description'] === undefined) return false;
    if (!('duration' in value) || value['duration'] === undefined) return false;
    if (!('genre' in value) || value['genre'] === undefined) return false;
    return true;
}

export function MovieAddRecordFromJSON(json: any): MovieAddRecord {
    return MovieAddRecordFromJSONTyped(json, false);
}

export function MovieAddRecordFromJSONTyped(json: any, ignoreDiscriminator: boolean): MovieAddRecord {
    if (json == null) {
        return json;
    }
    return {
        
        'title': json['title'],
        'description': json['description'],
        'duration': json['duration'],
        'genre': GenreEnumFromJSON(json['genre']),
    };
}

export function MovieAddRecordToJSON(json: any): MovieAddRecord {
    return MovieAddRecordToJSONTyped(json, false);
}

export function MovieAddRecordToJSONTyped(value?: MovieAddRecord | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'title': value['title'],
        'description': value['description'],
        'duration': value['duration'],
        'genre': GenreEnumToJSON(value['genre']),
    };
}

