/* tslint:disable */
/* eslint-disable */
/**
 * CineReserve
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { MovieRecord } from './MovieRecord';
import {
    MovieRecordFromJSON,
    MovieRecordFromJSONTyped,
    MovieRecordToJSON,
    MovieRecordToJSONTyped,
} from './MovieRecord';
import type { ErrorMessage } from './ErrorMessage';
import {
    ErrorMessageFromJSON,
    ErrorMessageFromJSONTyped,
    ErrorMessageToJSON,
    ErrorMessageToJSONTyped,
} from './ErrorMessage';

/**
 * 
 * @export
 * @interface MovieRecordRequestResponse
 */
export interface MovieRecordRequestResponse {
    /**
     * 
     * @type {MovieRecord}
     * @memberof MovieRecordRequestResponse
     */
    readonly response?: MovieRecord | null;
    /**
     * 
     * @type {ErrorMessage}
     * @memberof MovieRecordRequestResponse
     */
    readonly errorMessage?: ErrorMessage | null;
}

/**
 * Check if a given object implements the MovieRecordRequestResponse interface.
 */
export function instanceOfMovieRecordRequestResponse(value: object): value is MovieRecordRequestResponse {
    return true;
}

export function MovieRecordRequestResponseFromJSON(json: any): MovieRecordRequestResponse {
    return MovieRecordRequestResponseFromJSONTyped(json, false);
}

export function MovieRecordRequestResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): MovieRecordRequestResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'response': json['response'] == null ? undefined : MovieRecordFromJSON(json['response']),
        'errorMessage': json['errorMessage'] == null ? undefined : ErrorMessageFromJSON(json['errorMessage']),
    };
}

export function MovieRecordRequestResponseToJSON(json: any): MovieRecordRequestResponse {
    return MovieRecordRequestResponseToJSONTyped(json, false);
}

export function MovieRecordRequestResponseToJSONTyped(value?: Omit<MovieRecordRequestResponse, 'response'|'errorMessage'> | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
    };
}

