/* tslint:disable */
/* eslint-disable */
/**
 * CineReserve
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ScreeningRecord } from './ScreeningRecord';
import {
    ScreeningRecordFromJSON,
    ScreeningRecordFromJSONTyped,
    ScreeningRecordToJSON,
    ScreeningRecordToJSONTyped,
} from './ScreeningRecord';
import type { ErrorMessage } from './ErrorMessage';
import {
    ErrorMessageFromJSON,
    ErrorMessageFromJSONTyped,
    ErrorMessageToJSON,
    ErrorMessageToJSONTyped,
} from './ErrorMessage';

/**
 * 
 * @export
 * @interface ScreeningRecordRequestResponse
 */
export interface ScreeningRecordRequestResponse {
    /**
     * 
     * @type {ScreeningRecord}
     * @memberof ScreeningRecordRequestResponse
     */
    readonly response?: ScreeningRecord | null;
    /**
     * 
     * @type {ErrorMessage}
     * @memberof ScreeningRecordRequestResponse
     */
    readonly errorMessage?: ErrorMessage | null;
}

/**
 * Check if a given object implements the ScreeningRecordRequestResponse interface.
 */
export function instanceOfScreeningRecordRequestResponse(value: object): value is ScreeningRecordRequestResponse {
    return true;
}

export function ScreeningRecordRequestResponseFromJSON(json: any): ScreeningRecordRequestResponse {
    return ScreeningRecordRequestResponseFromJSONTyped(json, false);
}

export function ScreeningRecordRequestResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ScreeningRecordRequestResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'response': json['response'] == null ? undefined : ScreeningRecordFromJSON(json['response']),
        'errorMessage': json['errorMessage'] == null ? undefined : ErrorMessageFromJSON(json['errorMessage']),
    };
}

export function ScreeningRecordRequestResponseToJSON(json: any): ScreeningRecordRequestResponse {
    return ScreeningRecordRequestResponseToJSONTyped(json, false);
}

export function ScreeningRecordRequestResponseToJSONTyped(value?: Omit<ScreeningRecordRequestResponse, 'response'|'errorMessage'> | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
    };
}

