/* tslint:disable */
/* eslint-disable */
/**
 * CineReserve
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ScreeningRecord } from './ScreeningRecord';
import {
    ScreeningRecordFromJSON,
    ScreeningRecordFromJSONTyped,
    ScreeningRecordToJSON,
    ScreeningRecordToJSONTyped,
} from './ScreeningRecord';

/**
 * 
 * @export
 * @interface ScreeningRecordPagedResponse
 */
export interface ScreeningRecordPagedResponse {
    /**
     * 
     * @type {number}
     * @memberof ScreeningRecordPagedResponse
     */
    page: number;
    /**
     * 
     * @type {number}
     * @memberof ScreeningRecordPagedResponse
     */
    pageSize: number;
    /**
     * 
     * @type {number}
     * @memberof ScreeningRecordPagedResponse
     */
    totalCount: number;
    /**
     * 
     * @type {Array<ScreeningRecord>}
     * @memberof ScreeningRecordPagedResponse
     */
    data: Array<ScreeningRecord>;
}

/**
 * Check if a given object implements the ScreeningRecordPagedResponse interface.
 */
export function instanceOfScreeningRecordPagedResponse(value: object): value is ScreeningRecordPagedResponse {
    if (!('page' in value) || value['page'] === undefined) return false;
    if (!('pageSize' in value) || value['pageSize'] === undefined) return false;
    if (!('totalCount' in value) || value['totalCount'] === undefined) return false;
    if (!('data' in value) || value['data'] === undefined) return false;
    return true;
}

export function ScreeningRecordPagedResponseFromJSON(json: any): ScreeningRecordPagedResponse {
    return ScreeningRecordPagedResponseFromJSONTyped(json, false);
}

export function ScreeningRecordPagedResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ScreeningRecordPagedResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'page': json['page'],
        'pageSize': json['pageSize'],
        'totalCount': json['totalCount'],
        'data': ((json['data'] as Array<any>).map(ScreeningRecordFromJSON)),
    };
}

export function ScreeningRecordPagedResponseToJSON(json: any): ScreeningRecordPagedResponse {
    return ScreeningRecordPagedResponseToJSONTyped(json, false);
}

export function ScreeningRecordPagedResponseToJSONTyped(value?: ScreeningRecordPagedResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'page': value['page'],
        'pageSize': value['pageSize'],
        'totalCount': value['totalCount'],
        'data': ((value['data'] as Array<any>).map(ScreeningRecordToJSON)),
    };
}

