/* tslint:disable */
/* eslint-disable */
/**
 * CineReserve
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ScreeningRecordPagedResponse } from './ScreeningRecordPagedResponse';
import {
    ScreeningRecordPagedResponseFromJSON,
    ScreeningRecordPagedResponseFromJSONTyped,
    ScreeningRecordPagedResponseToJSON,
    ScreeningRecordPagedResponseToJSONTyped,
} from './ScreeningRecordPagedResponse';
import type { ErrorMessage } from './ErrorMessage';
import {
    ErrorMessageFromJSON,
    ErrorMessageFromJSONTyped,
    ErrorMessageToJSON,
    ErrorMessageToJSONTyped,
} from './ErrorMessage';

/**
 * 
 * @export
 * @interface ScreeningRecordPagedResponseRequestResponse
 */
export interface ScreeningRecordPagedResponseRequestResponse {
    /**
     * 
     * @type {ScreeningRecordPagedResponse}
     * @memberof ScreeningRecordPagedResponseRequestResponse
     */
    readonly response?: ScreeningRecordPagedResponse | null;
    /**
     * 
     * @type {ErrorMessage}
     * @memberof ScreeningRecordPagedResponseRequestResponse
     */
    readonly errorMessage?: ErrorMessage | null;
}

/**
 * Check if a given object implements the ScreeningRecordPagedResponseRequestResponse interface.
 */
export function instanceOfScreeningRecordPagedResponseRequestResponse(value: object): value is ScreeningRecordPagedResponseRequestResponse {
    return true;
}

export function ScreeningRecordPagedResponseRequestResponseFromJSON(json: any): ScreeningRecordPagedResponseRequestResponse {
    return ScreeningRecordPagedResponseRequestResponseFromJSONTyped(json, false);
}

export function ScreeningRecordPagedResponseRequestResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ScreeningRecordPagedResponseRequestResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'response': json['response'] == null ? undefined : ScreeningRecordPagedResponseFromJSON(json['response']),
        'errorMessage': json['errorMessage'] == null ? undefined : ErrorMessageFromJSON(json['errorMessage']),
    };
}

export function ScreeningRecordPagedResponseRequestResponseToJSON(json: any): ScreeningRecordPagedResponseRequestResponse {
    return ScreeningRecordPagedResponseRequestResponseToJSONTyped(json, false);
}

export function ScreeningRecordPagedResponseRequestResponseToJSONTyped(value?: Omit<ScreeningRecordPagedResponseRequestResponse, 'response'|'errorMessage'> | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
    };
}

