/* tslint:disable */
/* eslint-disable */
/**
 * CineReserve
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ScreenEnum } from './ScreenEnum';
import {
    ScreenEnumFromJSON,
    ScreenEnumFromJSONTyped,
    ScreenEnumToJSON,
    ScreenEnumToJSONTyped,
} from './ScreenEnum';

/**
 * 
 * @export
 * @interface ScreeningAddRecord
 */
export interface ScreeningAddRecord {
    /**
     * 
     * @type {Date}
     * @memberof ScreeningAddRecord
     */
    startTime: Date;
    /**
     * 
     * @type {string}
     * @memberof ScreeningAddRecord
     */
    movieId: string;
    /**
     * 
     * @type {string}
     * @memberof ScreeningAddRecord
     */
    hallId: string;
    /**
     * 
     * @type {ScreenEnum}
     * @memberof ScreeningAddRecord
     */
    screenType: ScreenEnum;
}



/**
 * Check if a given object implements the ScreeningAddRecord interface.
 */
export function instanceOfScreeningAddRecord(value: object): value is ScreeningAddRecord {
    if (!('startTime' in value) || value['startTime'] === undefined) return false;
    if (!('movieId' in value) || value['movieId'] === undefined) return false;
    if (!('hallId' in value) || value['hallId'] === undefined) return false;
    if (!('screenType' in value) || value['screenType'] === undefined) return false;
    return true;
}

export function ScreeningAddRecordFromJSON(json: any): ScreeningAddRecord {
    return ScreeningAddRecordFromJSONTyped(json, false);
}

export function ScreeningAddRecordFromJSONTyped(json: any, ignoreDiscriminator: boolean): ScreeningAddRecord {
    if (json == null) {
        return json;
    }
    return {
        
        'startTime': (new Date(json['startTime'])),
        'movieId': json['movieId'],
        'hallId': json['hallId'],
        'screenType': ScreenEnumFromJSON(json['screenType']),
    };
}

export function ScreeningAddRecordToJSON(json: any): ScreeningAddRecord {
    return ScreeningAddRecordToJSONTyped(json, false);
}

export function ScreeningAddRecordToJSONTyped(value?: ScreeningAddRecord | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'startTime': ((value['startTime']).toISOString()),
        'movieId': value['movieId'],
        'hallId': value['hallId'],
        'screenType': ScreenEnumToJSON(value['screenType']),
    };
}

