global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'auth-service'
    dns_sd_configs:
      - names: ['tasks.cinereserve-auth-service']
        type: 'A'
        port: 8080

  - job_name: 'catalog-service'
    dns_sd_configs:
      - names: ['tasks.cinereserve-catalog-service']
        type: 'A'
        port: 8080

  - job_name: 'booking-service'
    dns_sd_configs:
      - names: ['tasks.cinereserve-booking-service']
        type: 'A'
        port: 8080