/* tslint:disable */
/* eslint-disable */
/**
 * CineReserve
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';

import type {
    LoginRecord,

} from '@infrastructure/apis/client/models/LoginRecord';
import {LoginRecordToJSON,
    LoginRecordFromJSON,
    LoginRecordToJSONTyped} from '@infrastructure/apis/client/models/LoginRecord';
import type {
    UserAddRecord
} from '@infrastructure/apis/client/models/UserAddRecord';

import {
    LoginResponseRecordRequestResponseFromJSON,
    LoginResponseRecordRequestResponseToJSON,
} from '@infrastructure/apis/client/models/LoginResponseRecordRequestResponse';
import type {
    LoginResponseRecordRequestResponse
} from '@infrastructure/apis/client/models/LoginResponseRecordRequestResponse';
import  {

    UserAddRecordFromJSON,
    UserAddRecordToJSON,
} from '@infrastructure/apis/client/models/UserAddRecord';


export interface ApiAuthorizationLoginPostRequest {
    loginRecord?: LoginRecord;
}

export interface ApiAuthorizationRegisterPostRequest {
    userAddRecord?: UserAddRecord;
}

/**
 * 
 */
export class AuthorizationApi extends runtime.BaseAPI {

    /**
     */
    async apiAuthorizationLoginPostRaw(requestParameters: ApiAuthorizationLoginPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<LoginResponseRecordRequestResponse>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("Bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/Authorization/Login`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: LoginRecordToJSON(requestParameters['loginRecord']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => LoginResponseRecordRequestResponseFromJSON(jsonValue));
    }

    /**
     */
    async apiAuthorizationLoginPost(requestParameters: ApiAuthorizationLoginPostRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<LoginResponseRecordRequestResponse> {
        const response = await this.apiAuthorizationLoginPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async apiAuthorizationRegisterPostRaw(requestParameters: ApiAuthorizationRegisterPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<LoginResponseRecordRequestResponse>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("Bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/Authorization/Register`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: UserAddRecordToJSON(requestParameters['userAddRecord']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => LoginResponseRecordRequestResponseFromJSON(jsonValue));
    }

    /**
     */
    async apiAuthorizationRegisterPost(requestParameters: ApiAuthorizationRegisterPostRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<LoginResponseRecordRequestResponse> {
        const response = await this.apiAuthorizationRegisterPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
