/* tslint:disable */
/* eslint-disable */
/**
 * CineReserve
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface BookingAddRecord
 */
export interface BookingAddRecord {
    /**
     * 
     * @type {string}
     * @memberof BookingAddRecord
     */
    screeningId: string;
}

/**
 * Check if a given object implements the BookingAddRecord interface.
 */
export function instanceOfBookingAddRecord(value: object): value is BookingAddRecord {
    if (!('screeningId' in value) || value['screeningId'] === undefined) return false;
    return true;
}

export function BookingAddRecordFromJSON(json: any): BookingAddRecord {
    return BookingAddRecordFromJSONTyped(json, false);
}

export function BookingAddRecordFromJSONTyped(json: any, ignoreDiscriminator: boolean): BookingAddRecord {
    if (json == null) {
        return json;
    }
    return {
        
        'screeningId': json['screeningId'],
    };
}

export function BookingAddRecordToJSON(json: any): BookingAddRecord {
    return BookingAddRecordToJSONTyped(json, false);
}

export function BookingAddRecordToJSONTyped(value?: BookingAddRecord | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'screeningId': value['screeningId'],
    };
}

