/* tslint:disable */
/* eslint-disable */
/**
 * CineReserve
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { FeedbackRecord } from './FeedbackRecord';
import {
    FeedbackRecordFromJSON,
    FeedbackRecordFromJSONTyped,
    FeedbackRecordToJSON,
    FeedbackRecordToJSONTyped,
} from './FeedbackRecord';

/**
 * 
 * @export
 * @interface FeedbackRecordPagedResponse
 */
export interface FeedbackRecordPagedResponse {
    /**
     * 
     * @type {number}
     * @memberof FeedbackRecordPagedResponse
     */
    page: number;
    /**
     * 
     * @type {number}
     * @memberof FeedbackRecordPagedResponse
     */
    pageSize: number;
    /**
     * 
     * @type {number}
     * @memberof FeedbackRecordPagedResponse
     */
    totalCount: number;
    /**
     * 
     * @type {Array<FeedbackRecord>}
     * @memberof FeedbackRecordPagedResponse
     */
    data: Array<FeedbackRecord>;
}

/**
 * Check if a given object implements the FeedbackRecordPagedResponse interface.
 */
export function instanceOfFeedbackRecordPagedResponse(value: object): value is FeedbackRecordPagedResponse {
    if (!('page' in value) || value['page'] === undefined) return false;
    if (!('pageSize' in value) || value['pageSize'] === undefined) return false;
    if (!('totalCount' in value) || value['totalCount'] === undefined) return false;
    if (!('data' in value) || value['data'] === undefined) return false;
    return true;
}

export function FeedbackRecordPagedResponseFromJSON(json: any): FeedbackRecordPagedResponse {
    return FeedbackRecordPagedResponseFromJSONTyped(json, false);
}

export function FeedbackRecordPagedResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): FeedbackRecordPagedResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'page': json['page'],
        'pageSize': json['pageSize'],
        'totalCount': json['totalCount'],
        'data': ((json['data'] as Array<any>).map(FeedbackRecordFromJSON)),
    };
}

export function FeedbackRecordPagedResponseToJSON(json: any): FeedbackRecordPagedResponse {
    return FeedbackRecordPagedResponseToJSONTyped(json, false);
}

export function FeedbackRecordPagedResponseToJSONTyped(value?: FeedbackRecordPagedResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'page': value['page'],
        'pageSize': value['pageSize'],
        'totalCount': value['totalCount'],
        'data': ((value['data'] as Array<any>).map(FeedbackRecordToJSON)),
    };
}

