/* tslint:disable */
/* eslint-disable */
/**
 * CineReserve
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface HallAddRecord
 */
export interface HallAddRecord {
    /**
     * 
     * @type {string}
     * @memberof HallAddRecord
     */
    name: string;
    /**
     * 
     * @type {number}
     * @memberof HallAddRecord
     */
    capacity: number;
}

/**
 * Check if a given object implements the HallAddRecord interface.
 */
export function instanceOfHallAddRecord(value: object): value is HallAddRecord {
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('capacity' in value) || value['capacity'] === undefined) return false;
    return true;
}

export function HallAddRecordFromJSON(json: any): HallAddRecord {
    return HallAddRecordFromJSONTyped(json, false);
}

export function HallAddRecordFromJSONTyped(json: any, ignoreDiscriminator: boolean): HallAddRecord {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
        'capacity': json['capacity'],
    };
}

export function HallAddRecordToJSON(json: any): HallAddRecord {
    return HallAddRecordToJSONTyped(json, false);
}

export function HallAddRecordToJSONTyped(value?: HallAddRecord | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'capacity': value['capacity'],
    };
}

