/* tslint:disable */
/* eslint-disable */
/**
 * CineReserve
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { HallRecord } from './HallRecord';
import {
    HallRecordFromJSON,
    HallRecordFromJSONTyped,
    HallRecordToJSON,
    HallRecordToJSONTyped,
} from './HallRecord';

/**
 * 
 * @export
 * @interface HallRecordPagedResponse
 */
export interface HallRecordPagedResponse {
    /**
     * 
     * @type {number}
     * @memberof HallRecordPagedResponse
     */
    page: number;
    /**
     * 
     * @type {number}
     * @memberof HallRecordPagedResponse
     */
    pageSize: number;
    /**
     * 
     * @type {number}
     * @memberof HallRecordPagedResponse
     */
    totalCount: number;
    /**
     * 
     * @type {Array<HallRecord>}
     * @memberof HallRecordPagedResponse
     */
    data: Array<HallRecord>;
}

/**
 * Check if a given object implements the HallRecordPagedResponse interface.
 */
export function instanceOfHallRecordPagedResponse(value: object): value is HallRecordPagedResponse {
    if (!('page' in value) || value['page'] === undefined) return false;
    if (!('pageSize' in value) || value['pageSize'] === undefined) return false;
    if (!('totalCount' in value) || value['totalCount'] === undefined) return false;
    if (!('data' in value) || value['data'] === undefined) return false;
    return true;
}

export function HallRecordPagedResponseFromJSON(json: any): HallRecordPagedResponse {
    return HallRecordPagedResponseFromJSONTyped(json, false);
}

export function HallRecordPagedResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): HallRecordPagedResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'page': json['page'],
        'pageSize': json['pageSize'],
        'totalCount': json['totalCount'],
        'data': ((json['data'] as Array<any>).map(HallRecordFromJSON)),
    };
}

export function HallRecordPagedResponseToJSON(json: any): HallRecordPagedResponse {
    return HallRecordPagedResponseToJSONTyped(json, false);
}

export function HallRecordPagedResponseToJSONTyped(value?: HallRecordPagedResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'page': value['page'],
        'pageSize': value['pageSize'],
        'totalCount': value['totalCount'],
        'data': ((value['data'] as Array<any>).map(HallRecordToJSON)),
    };
}

