/* tslint:disable */
/* eslint-disable */
/**
 * CineReserve
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface HallUpdateRecord
 */
export interface HallUpdateRecord {
    /**
     * 
     * @type {string}
     * @memberof HallUpdateRecord
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof HallUpdateRecord
     */
    name?: string | null;
    /**
     * 
     * @type {number}
     * @memberof HallUpdateRecord
     */
    capacity?: number | null;
}

/**
 * Check if a given object implements the HallUpdateRecord interface.
 */
export function instanceOfHallUpdateRecord(value: object): value is HallUpdateRecord {
    if (!('id' in value) || value['id'] === undefined) return false;
    return true;
}

export function HallUpdateRecordFromJSON(json: any): HallUpdateRecord {
    return HallUpdateRecordFromJSONTyped(json, false);
}

export function HallUpdateRecordFromJSONTyped(json: any, ignoreDiscriminator: boolean): HallUpdateRecord {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'name': json['name'] == null ? undefined : json['name'],
        'capacity': json['capacity'] == null ? undefined : json['capacity'],
    };
}

export function HallUpdateRecordToJSON(json: any): HallUpdateRecord {
    return HallUpdateRecordToJSONTyped(json, false);
}

export function HallUpdateRecordToJSONTyped(value?: HallUpdateRecord | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
        'capacity': value['capacity'],
    };
}

