/* tslint:disable */
/* eslint-disable */
/**
 * CineReserve
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { MovieRecord } from './MovieRecord';
import {
    MovieRecordFromJSON,
    MovieRecordFromJSONTyped,
    MovieRecordToJSON,
    MovieRecordToJSONTyped,
} from './MovieRecord';

/**
 * 
 * @export
 * @interface MovieRecordPagedResponse
 */
export interface MovieRecordPagedResponse {
    /**
     * 
     * @type {number}
     * @memberof MovieRecordPagedResponse
     */
    page: number;
    /**
     * 
     * @type {number}
     * @memberof MovieRecordPagedResponse
     */
    pageSize: number;
    /**
     * 
     * @type {number}
     * @memberof MovieRecordPagedResponse
     */
    totalCount: number;
    /**
     * 
     * @type {Array<MovieRecord>}
     * @memberof MovieRecordPagedResponse
     */
    data: Array<MovieRecord>;
}

/**
 * Check if a given object implements the MovieRecordPagedResponse interface.
 */
export function instanceOfMovieRecordPagedResponse(value: object): value is MovieRecordPagedResponse {
    if (!('page' in value) || value['page'] === undefined) return false;
    if (!('pageSize' in value) || value['pageSize'] === undefined) return false;
    if (!('totalCount' in value) || value['totalCount'] === undefined) return false;
    if (!('data' in value) || value['data'] === undefined) return false;
    return true;
}

export function MovieRecordPagedResponseFromJSON(json: any): MovieRecordPagedResponse {
    return MovieRecordPagedResponseFromJSONTyped(json, false);
}

export function MovieRecordPagedResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): MovieRecordPagedResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'page': json['page'],
        'pageSize': json['pageSize'],
        'totalCount': json['totalCount'],
        'data': ((json['data'] as Array<any>).map(MovieRecordFromJSON)),
    };
}

export function MovieRecordPagedResponseToJSON(json: any): MovieRecordPagedResponse {
    return MovieRecordPagedResponseToJSONTyped(json, false);
}

export function MovieRecordPagedResponseToJSONTyped(value?: MovieRecordPagedResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'page': value['page'],
        'pageSize': value['pageSize'],
        'totalCount': value['totalCount'],
        'data': ((value['data'] as Array<any>).map(MovieRecordToJSON)),
    };
}

