/* tslint:disable */
/* eslint-disable */
/**
 * CineReserve
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const ScreenEnum = {
    TwoD: 'TWO_D',
    ThreeD: 'THREE_D',
    FourD: 'FOUR_D',
    FourDx: 'FOUR_DX'
} as const;
export type ScreenEnum = typeof ScreenEnum[keyof typeof ScreenEnum];


export function instanceOfScreenEnum(value: any): boolean {
    for (const key in ScreenEnum) {
        if (Object.prototype.hasOwnProperty.call(ScreenEnum, key)) {
            if (ScreenEnum[key as keyof typeof ScreenEnum] === value) {
                return true;
            }
        }
    }
    return false;
}

export function ScreenEnumFromJSON(json: any): ScreenEnum {
    return ScreenEnumFromJSONTyped(json, false);
}

export function ScreenEnumFromJSONTyped(json: any, ignoreDiscriminator: boolean): ScreenEnum {
    return json as ScreenEnum;
}

export function ScreenEnumToJSON(value?: ScreenEnum | null): any {
    return value as any;
}

export function ScreenEnumToJSONTyped(value: any, ignoreDiscriminator: boolean): ScreenEnum {
    return value as ScreenEnum;
}

