/* tslint:disable */
/* eslint-disable */
/**
 * CineReserve
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ScreenEnum } from './ScreenEnum';
import {
    ScreenEnumFromJSON,
    ScreenEnumFromJSONTyped,
    ScreenEnumToJSON,
    ScreenEnumToJSONTyped,
} from './ScreenEnum';
import type { MovieRecord } from './MovieRecord';
import {
    MovieRecordFromJSON,
    MovieRecordFromJSONTyped,
    MovieRecordToJSON,
    MovieRecordToJSONTyped,
} from './MovieRecord';
import type { HallRecord } from './HallRecord';
import {
    HallRecordFromJSON,
    HallRecordFromJSONTyped,
    HallRecordToJSON,
    HallRecordToJSONTyped,
} from './HallRecord';

/**
 * 
 * @export
 * @interface ScreeningRecord
 */
export interface ScreeningRecord {
    /**
     * 
     * @type {string}
     * @memberof ScreeningRecord
     */
    id: string;
    /**
     * 
     * @type {Date}
     * @memberof ScreeningRecord
     */
    startTime: Date;
    /**
     * 
     * @type {string}
     * @memberof ScreeningRecord
     */
    movieId: string;
    /**
     * 
     * @type {MovieRecord}
     * @memberof ScreeningRecord
     */
    movie: MovieRecord;
    /**
     * 
     * @type {string}
     * @memberof ScreeningRecord
     */
    hallId: string;
    /**
     * 
     * @type {HallRecord}
     * @memberof ScreeningRecord
     */
    hall: HallRecord;
    /**
     * 
     * @type {ScreenEnum}
     * @memberof ScreeningRecord
     */
    screenType: ScreenEnum;
}



/**
 * Check if a given object implements the ScreeningRecord interface.
 */
export function instanceOfScreeningRecord(value: object): value is ScreeningRecord {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('startTime' in value) || value['startTime'] === undefined) return false;
    if (!('movieId' in value) || value['movieId'] === undefined) return false;
    if (!('movie' in value) || value['movie'] === undefined) return false;
    if (!('hallId' in value) || value['hallId'] === undefined) return false;
    if (!('hall' in value) || value['hall'] === undefined) return false;
    if (!('screenType' in value) || value['screenType'] === undefined) return false;
    return true;
}

export function ScreeningRecordFromJSON(json: any): ScreeningRecord {
    return ScreeningRecordFromJSONTyped(json, false);
}

export function ScreeningRecordFromJSONTyped(json: any, ignoreDiscriminator: boolean): ScreeningRecord {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'startTime': (new Date(json['startTime'])),
        'movieId': json['movieId'],
        'movie': MovieRecordFromJSON(json['movie']),
        'hallId': json['hallId'],
        'hall': HallRecordFromJSON(json['hall']),
        'screenType': ScreenEnumFromJSON(json['screenType']),
    };
}

export function ScreeningRecordToJSON(json: any): ScreeningRecord {
    return ScreeningRecordToJSONTyped(json, false);
}

export function ScreeningRecordToJSONTyped(value?: ScreeningRecord | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'startTime': ((value['startTime']).toISOString()),
        'movieId': value['movieId'],
        'movie': MovieRecordToJSON(value['movie']),
        'hallId': value['hallId'],
        'hall': HallRecordToJSON(value['hall']),
        'screenType': ScreenEnumToJSON(value['screenType']),
    };
}

