/* tslint:disable */
/* eslint-disable */
/**
 * CineReserve
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  HallAddRecord,
  HallRecordPagedResponseRequestResponse,
  HallRecordRequestResponse,
  HallUpdateRecord,
  RequestResponse,
} from '../models/index';
import {
    HallAddRecordFromJSON,
    HallAddRecordToJSON,
    HallRecordPagedResponseRequestResponseFromJSON,
    HallRecordPagedResponseRequestResponseToJSON,
    HallRecordRequestResponseFromJSON,
    HallRecordRequestResponseToJSON,
    HallUpdateRecordFromJSON,
    HallUpdateRecordToJSON,
    RequestResponseFromJSON,
    RequestResponseToJSON,
} from '../models/index';

export interface ApiHallAddPostRequest {
    hallAddRecord?: HallAddRecord;
}

export interface ApiHallDeleteIdDeleteRequest {
    id: string;
}

export interface ApiHallGetByIdIdGetRequest {
    id: string;
}

export interface ApiHallGetPageGetRequest {
    search?: string;
    page?: number;
    pageSize?: number;
}

export interface ApiHallUpdatePutRequest {
    hallUpdateRecord?: HallUpdateRecord;
}

/**
 * 
 */
export class HallApi extends runtime.BaseAPI {

    /**
     */
    async apiHallAddPostRaw(requestParameters: ApiHallAddPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<RequestResponse>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("Bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/Hall/Add`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: HallAddRecordToJSON(requestParameters['hallAddRecord']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => RequestResponseFromJSON(jsonValue));
    }

    /**
     */
    async apiHallAddPost(requestParameters: ApiHallAddPostRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<RequestResponse> {
        const response = await this.apiHallAddPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async apiHallDeleteIdDeleteRaw(requestParameters: ApiHallDeleteIdDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<RequestResponse>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling apiHallDeleteIdDelete().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("Bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/Hall/Delete/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => RequestResponseFromJSON(jsonValue));
    }

    /**
     */
    async apiHallDeleteIdDelete(requestParameters: ApiHallDeleteIdDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<RequestResponse> {
        const response = await this.apiHallDeleteIdDeleteRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async apiHallGetByIdIdGetRaw(requestParameters: ApiHallGetByIdIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<HallRecordRequestResponse>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling apiHallGetByIdIdGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("Bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/Hall/GetById/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => HallRecordRequestResponseFromJSON(jsonValue));
    }

    /**
     */
    async apiHallGetByIdIdGet(requestParameters: ApiHallGetByIdIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<HallRecordRequestResponse> {
        const response = await this.apiHallGetByIdIdGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async apiHallGetPageGetRaw(requestParameters: ApiHallGetPageGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<HallRecordPagedResponseRequestResponse>> {
        const queryParameters: any = {};

        if (requestParameters['search'] != null) {
            queryParameters['Search'] = requestParameters['search'];
        }

        if (requestParameters['page'] != null) {
            queryParameters['Page'] = requestParameters['page'];
        }

        if (requestParameters['pageSize'] != null) {
            queryParameters['PageSize'] = requestParameters['pageSize'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("Bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/Hall/GetPage`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => HallRecordPagedResponseRequestResponseFromJSON(jsonValue));
    }

    /**
     */
    async apiHallGetPageGet(requestParameters: ApiHallGetPageGetRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<HallRecordPagedResponseRequestResponse> {
        const response = await this.apiHallGetPageGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async apiHallUpdatePutRaw(requestParameters: ApiHallUpdatePutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<RequestResponse>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("Bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/Hall/Update`,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: HallUpdateRecordToJSON(requestParameters['hallUpdateRecord']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => RequestResponseFromJSON(jsonValue));
    }

    /**
     */
    async apiHallUpdatePut(requestParameters: ApiHallUpdatePutRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<RequestResponse> {
        const response = await this.apiHallUpdatePutRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
