/* tslint:disable */
/* eslint-disable */
/**
 * CineReserve
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  RequestResponse,
  ScreeningAddRecord,
  ScreeningRecordPagedResponseRequestResponse,
  ScreeningRecordRequestResponse,
  ScreeningUpdateRecord,
} from '../models/index';
import {
    RequestResponseFromJSON,
    RequestResponseToJSON,
    ScreeningAddRecordFromJSON,
    ScreeningAddRecordToJSON,
    ScreeningRecordPagedResponseRequestResponseFromJSON,
    ScreeningRecordPagedResponseRequestResponseToJSON,
    ScreeningRecordRequestResponseFromJSON,
    ScreeningRecordRequestResponseToJSON,
    ScreeningUpdateRecordFromJSON,
    ScreeningUpdateRecordToJSON,
} from '../models/index';

export interface ApiScreeningAddPostRequest {
    screeningAddRecord?: ScreeningAddRecord;
}

export interface ApiScreeningDeleteIdDeleteRequest {
    id: string;
}

export interface ApiScreeningGetByIdIdGetRequest {
    id: string;
}

export interface ApiScreeningGetPageGetRequest {
    search?: string;
    page?: number;
    pageSize?: number;
}

export interface ApiScreeningUpdatePutRequest {
    screeningUpdateRecord?: ScreeningUpdateRecord;
}

/**
 * 
 */
export class ScreeningApi extends runtime.BaseAPI {

    /**
     */
    async apiScreeningAddPostRaw(requestParameters: ApiScreeningAddPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<RequestResponse>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("Bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/Screening/Add`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: ScreeningAddRecordToJSON(requestParameters['screeningAddRecord']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => RequestResponseFromJSON(jsonValue));
    }

    /**
     */
    async apiScreeningAddPost(requestParameters: ApiScreeningAddPostRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<RequestResponse> {
        const response = await this.apiScreeningAddPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async apiScreeningDeleteIdDeleteRaw(requestParameters: ApiScreeningDeleteIdDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<RequestResponse>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling apiScreeningDeleteIdDelete().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("Bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/Screening/Delete/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => RequestResponseFromJSON(jsonValue));
    }

    /**
     */
    async apiScreeningDeleteIdDelete(requestParameters: ApiScreeningDeleteIdDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<RequestResponse> {
        const response = await this.apiScreeningDeleteIdDeleteRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async apiScreeningGetByIdIdGetRaw(requestParameters: ApiScreeningGetByIdIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ScreeningRecordRequestResponse>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling apiScreeningGetByIdIdGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("Bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/Screening/GetById/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ScreeningRecordRequestResponseFromJSON(jsonValue));
    }

    /**
     */
    async apiScreeningGetByIdIdGet(requestParameters: ApiScreeningGetByIdIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ScreeningRecordRequestResponse> {
        const response = await this.apiScreeningGetByIdIdGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async apiScreeningGetPageGetRaw(requestParameters: ApiScreeningGetPageGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ScreeningRecordPagedResponseRequestResponse>> {
        const queryParameters: any = {};

        if (requestParameters['search'] != null) {
            queryParameters['Search'] = requestParameters['search'];
        }

        if (requestParameters['page'] != null) {
            queryParameters['Page'] = requestParameters['page'];
        }

        if (requestParameters['pageSize'] != null) {
            queryParameters['PageSize'] = requestParameters['pageSize'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("Bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/Screening/GetPage`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ScreeningRecordPagedResponseRequestResponseFromJSON(jsonValue));
    }

    /**
     */
    async apiScreeningGetPageGet(requestParameters: ApiScreeningGetPageGetRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ScreeningRecordPagedResponseRequestResponse> {
        const response = await this.apiScreeningGetPageGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async apiScreeningUpdatePutRaw(requestParameters: ApiScreeningUpdatePutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<RequestResponse>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("Bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/Screening/Update`,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: ScreeningUpdateRecordToJSON(requestParameters['screeningUpdateRecord']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => RequestResponseFromJSON(jsonValue));
    }

    /**
     */
    async apiScreeningUpdatePut(requestParameters: ApiScreeningUpdatePutRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<RequestResponse> {
        const response = await this.apiScreeningUpdatePutRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
