/* tslint:disable */
/* eslint-disable */
/**
 * CineReserve
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  BookingAddRecord,
  BookingRecordPagedResponseRequestResponse,
  BookingRecordRequestResponse,
  BookingUpdateRecord,
  RequestResponse,
} from '../models/index';
import {
    BookingAddRecordFromJSON,
    BookingAddRecordToJSON,
    BookingRecordPagedResponseRequestResponseFromJSON,
    BookingRecordPagedResponseRequestResponseToJSON,
    BookingRecordRequestResponseFromJSON,
    BookingRecordRequestResponseToJSON,
    BookingUpdateRecordFromJSON,
    BookingUpdateRecordToJSON,
    RequestResponseFromJSON,
    RequestResponseToJSON,
} from '../models/index';

export interface ApiBookingAddPostRequest {
    bookingAddRecord?: BookingAddRecord;
}

export interface ApiBookingDeleteIdDeleteRequest {
    id: string;
}

export interface ApiBookingGetByIdIdGetRequest {
    id: string;
}

export interface ApiBookingGetPageGetRequest {
    search?: string;
    page?: number;
    pageSize?: number;
}

export interface ApiBookingUpdatePutRequest {
    bookingUpdateRecord?: BookingUpdateRecord;
}

/**
 * 
 */
export class BookingApi extends runtime.BaseAPI {

    /**
     */
    async apiBookingAddPostRaw(requestParameters: ApiBookingAddPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<RequestResponse>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("Bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/Booking/Add`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: BookingAddRecordToJSON(requestParameters['bookingAddRecord']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => RequestResponseFromJSON(jsonValue));
    }

    /**
     */
    async apiBookingAddPost(requestParameters: ApiBookingAddPostRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<RequestResponse> {
        const response = await this.apiBookingAddPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async apiBookingDeleteIdDeleteRaw(requestParameters: ApiBookingDeleteIdDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<RequestResponse>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling apiBookingDeleteIdDelete().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("Bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/Booking/Delete/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => RequestResponseFromJSON(jsonValue));
    }

    /**
     */
    async apiBookingDeleteIdDelete(requestParameters: ApiBookingDeleteIdDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<RequestResponse> {
        const response = await this.apiBookingDeleteIdDeleteRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async apiBookingGetByIdIdGetRaw(requestParameters: ApiBookingGetByIdIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<BookingRecordRequestResponse>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling apiBookingGetByIdIdGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("Bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/Booking/GetById/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => BookingRecordRequestResponseFromJSON(jsonValue));
    }

    /**
     */
    async apiBookingGetByIdIdGet(requestParameters: ApiBookingGetByIdIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<BookingRecordRequestResponse> {
        const response = await this.apiBookingGetByIdIdGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async apiBookingGetPageGetRaw(requestParameters: ApiBookingGetPageGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<BookingRecordPagedResponseRequestResponse>> {
        const queryParameters: any = {};

        if (requestParameters['search'] != null) {
            queryParameters['Search'] = requestParameters['search'];
        }

        if (requestParameters['page'] != null) {
            queryParameters['Page'] = requestParameters['page'];
        }

        if (requestParameters['pageSize'] != null) {
            queryParameters['PageSize'] = requestParameters['pageSize'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("Bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/Booking/GetPage`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => BookingRecordPagedResponseRequestResponseFromJSON(jsonValue));
    }

    /**
     */
    async apiBookingGetPageGet(requestParameters: ApiBookingGetPageGetRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<BookingRecordPagedResponseRequestResponse> {
        const response = await this.apiBookingGetPageGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async apiBookingUpdatePutRaw(requestParameters: ApiBookingUpdatePutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<RequestResponse>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("Bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/Booking/Update`,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: BookingUpdateRecordToJSON(requestParameters['bookingUpdateRecord']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => RequestResponseFromJSON(jsonValue));
    }

    /**
     */
    async apiBookingUpdatePut(requestParameters: ApiBookingUpdatePutRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<RequestResponse> {
        const response = await this.apiBookingUpdatePutRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
