/* tslint:disable */
/* eslint-disable */
/**
 * CineReserve
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { UserRecord } from './UserRecord';
import {
    UserRecordFromJSON,
    UserRecordFromJSONTyped,
    UserRecordToJSON,
    UserRecordToJSONTyped,
} from './UserRecord';
import type { ScreeningRecord } from './ScreeningRecord';
import {
    ScreeningRecordFromJSON,
    ScreeningRecordFromJSONTyped,
    ScreeningRecordToJSON,
    ScreeningRecordToJSONTyped,
} from './ScreeningRecord';

/**
 * 
 * @export
 * @interface BookingRecord
 */
export interface BookingRecord {
    /**
     * 
     * @type {string}
     * @memberof BookingRecord
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof BookingRecord
     */
    userId: string;
    /**
     * 
     * @type {UserRecord}
     * @memberof BookingRecord
     */
    user: UserRecord;
    /**
     * 
     * @type {string}
     * @memberof BookingRecord
     */
    screeningId: string;
    /**
     * 
     * @type {ScreeningRecord}
     * @memberof BookingRecord
     */
    screening: ScreeningRecord;
}

/**
 * Check if a given object implements the BookingRecord interface.
 */
export function instanceOfBookingRecord(value: object): value is BookingRecord {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('userId' in value) || value['userId'] === undefined) return false;
    if (!('user' in value) || value['user'] === undefined) return false;
    if (!('screeningId' in value) || value['screeningId'] === undefined) return false;
    if (!('screening' in value) || value['screening'] === undefined) return false;
    return true;
}

export function BookingRecordFromJSON(json: any): BookingRecord {
    return BookingRecordFromJSONTyped(json, false);
}

export function BookingRecordFromJSONTyped(json: any, ignoreDiscriminator: boolean): BookingRecord {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'userId': json['userId'],
        'user': UserRecordFromJSON(json['user']),
        'screeningId': json['screeningId'],
        'screening': ScreeningRecordFromJSON(json['screening']),
    };
}

export function BookingRecordToJSON(json: any): BookingRecord {
    return BookingRecordToJSONTyped(json, false);
}

export function BookingRecordToJSONTyped(value?: BookingRecord | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'userId': value['userId'],
        'user': UserRecordToJSON(value['user']),
        'screeningId': value['screeningId'],
        'screening': ScreeningRecordToJSON(value['screening']),
    };
}

