/* tslint:disable */
/* eslint-disable */
/**
 * CineReserve
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { BookingRecord } from './BookingRecord';
import {
    BookingRecordFromJSON,
    BookingRecordFromJSONTyped,
    BookingRecordToJSON,
    BookingRecordToJSONTyped,
} from './BookingRecord';
import type { ErrorMessage } from './ErrorMessage';
import {
    ErrorMessageFromJSON,
    ErrorMessageFromJSONTyped,
    ErrorMessageToJSON,
    ErrorMessageToJSONTyped,
} from './ErrorMessage';

/**
 * 
 * @export
 * @interface BookingRecordRequestResponse
 */
export interface BookingRecordRequestResponse {
    /**
     * 
     * @type {BookingRecord}
     * @memberof BookingRecordRequestResponse
     */
    readonly response?: BookingRecord | null;
    /**
     * 
     * @type {ErrorMessage}
     * @memberof BookingRecordRequestResponse
     */
    readonly errorMessage?: ErrorMessage | null;
}

/**
 * Check if a given object implements the BookingRecordRequestResponse interface.
 */
export function instanceOfBookingRecordRequestResponse(value: object): value is BookingRecordRequestResponse {
    return true;
}

export function BookingRecordRequestResponseFromJSON(json: any): BookingRecordRequestResponse {
    return BookingRecordRequestResponseFromJSONTyped(json, false);
}

export function BookingRecordRequestResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): BookingRecordRequestResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'response': json['response'] == null ? undefined : BookingRecordFromJSON(json['response']),
        'errorMessage': json['errorMessage'] == null ? undefined : ErrorMessageFromJSON(json['errorMessage']),
    };
}

export function BookingRecordRequestResponseToJSON(json: any): BookingRecordRequestResponse {
    return BookingRecordRequestResponseToJSONTyped(json, false);
}

export function BookingRecordRequestResponseToJSONTyped(value?: Omit<BookingRecordRequestResponse, 'response'|'errorMessage'> | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
    };
}

