/* tslint:disable */
/* eslint-disable */
/**
 * CineReserve
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface FeedbackAddRecord
 */
export interface FeedbackAddRecord {
    /**
     * 
     * @type {number}
     * @memberof FeedbackAddRecord
     */
    rating: number;
    /**
     * 
     * @type {string}
     * @memberof FeedbackAddRecord
     */
    comment: string;
    /**
     * 
     * @type {boolean}
     * @memberof FeedbackAddRecord
     */
    wouldRecommend?: boolean | null;
    /**
     * 
     * @type {string}
     * @memberof FeedbackAddRecord
     */
    movieId: string;
}

/**
 * Check if a given object implements the FeedbackAddRecord interface.
 */
export function instanceOfFeedbackAddRecord(value: object): value is FeedbackAddRecord {
    if (!('rating' in value) || value['rating'] === undefined) return false;
    if (!('comment' in value) || value['comment'] === undefined) return false;
    if (!('movieId' in value) || value['movieId'] === undefined) return false;
    return true;
}

export function FeedbackAddRecordFromJSON(json: any): FeedbackAddRecord {
    return FeedbackAddRecordFromJSONTyped(json, false);
}

export function FeedbackAddRecordFromJSONTyped(json: any, ignoreDiscriminator: boolean): FeedbackAddRecord {
    if (json == null) {
        return json;
    }
    return {
        
        'rating': json['rating'],
        'comment': json['comment'],
        'wouldRecommend': json['wouldRecommend'] == null ? undefined : json['wouldRecommend'],
        'movieId': json['movieId'],
    };
}

export function FeedbackAddRecordToJSON(json: any): FeedbackAddRecord {
    return FeedbackAddRecordToJSONTyped(json, false);
}

export function FeedbackAddRecordToJSONTyped(value?: FeedbackAddRecord | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'rating': value['rating'],
        'comment': value['comment'],
        'wouldRecommend': value['wouldRecommend'],
        'movieId': value['movieId'],
    };
}

