/* tslint:disable */
/* eslint-disable */
/**
 * CineReserve
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ErrorMessage } from './ErrorMessage';
import {
    ErrorMessageFromJSON,
    ErrorMessageFromJSONTyped,
    ErrorMessageToJSON,
    ErrorMessageToJSONTyped,
} from './ErrorMessage';
import type { HallRecordPagedResponse } from './HallRecordPagedResponse';
import {
    HallRecordPagedResponseFromJSON,
    HallRecordPagedResponseFromJSONTyped,
    HallRecordPagedResponseToJSON,
    HallRecordPagedResponseToJSONTyped,
} from './HallRecordPagedResponse';

/**
 * 
 * @export
 * @interface HallRecordPagedResponseRequestResponse
 */
export interface HallRecordPagedResponseRequestResponse {
    /**
     * 
     * @type {HallRecordPagedResponse}
     * @memberof HallRecordPagedResponseRequestResponse
     */
    readonly response?: HallRecordPagedResponse | null;
    /**
     * 
     * @type {ErrorMessage}
     * @memberof HallRecordPagedResponseRequestResponse
     */
    readonly errorMessage?: ErrorMessage | null;
}

/**
 * Check if a given object implements the HallRecordPagedResponseRequestResponse interface.
 */
export function instanceOfHallRecordPagedResponseRequestResponse(value: object): value is HallRecordPagedResponseRequestResponse {
    return true;
}

export function HallRecordPagedResponseRequestResponseFromJSON(json: any): HallRecordPagedResponseRequestResponse {
    return HallRecordPagedResponseRequestResponseFromJSONTyped(json, false);
}

export function HallRecordPagedResponseRequestResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): HallRecordPagedResponseRequestResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'response': json['response'] == null ? undefined : HallRecordPagedResponseFromJSON(json['response']),
        'errorMessage': json['errorMessage'] == null ? undefined : ErrorMessageFromJSON(json['errorMessage']),
    };
}

export function HallRecordPagedResponseRequestResponseToJSON(json: any): HallRecordPagedResponseRequestResponse {
    return HallRecordPagedResponseRequestResponseToJSONTyped(json, false);
}

export function HallRecordPagedResponseRequestResponseToJSONTyped(value?: Omit<HallRecordPagedResponseRequestResponse, 'response'|'errorMessage'> | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
    };
}

