/* tslint:disable */
/* eslint-disable */
/**
 * CineReserve
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ErrorMessage } from './ErrorMessage';
import {
    ErrorMessageFromJSON,
    ErrorMessageFromJSONTyped,
    ErrorMessageToJSON,
    ErrorMessageToJSONTyped,
} from './ErrorMessage';
import type { MovieRecordPagedResponse } from './MovieRecordPagedResponse';
import {
    MovieRecordPagedResponseFromJSON,
    MovieRecordPagedResponseFromJSONTyped,
    MovieRecordPagedResponseToJSON,
    MovieRecordPagedResponseToJSONTyped,
} from './MovieRecordPagedResponse';

/**
 * 
 * @export
 * @interface MovieRecordPagedResponseRequestResponse
 */
export interface MovieRecordPagedResponseRequestResponse {
    /**
     * 
     * @type {MovieRecordPagedResponse}
     * @memberof MovieRecordPagedResponseRequestResponse
     */
    readonly response?: MovieRecordPagedResponse | null;
    /**
     * 
     * @type {ErrorMessage}
     * @memberof MovieRecordPagedResponseRequestResponse
     */
    readonly errorMessage?: ErrorMessage | null;
}

/**
 * Check if a given object implements the MovieRecordPagedResponseRequestResponse interface.
 */
export function instanceOfMovieRecordPagedResponseRequestResponse(value: object): value is MovieRecordPagedResponseRequestResponse {
    return true;
}

export function MovieRecordPagedResponseRequestResponseFromJSON(json: any): MovieRecordPagedResponseRequestResponse {
    return MovieRecordPagedResponseRequestResponseFromJSONTyped(json, false);
}

export function MovieRecordPagedResponseRequestResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): MovieRecordPagedResponseRequestResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'response': json['response'] == null ? undefined : MovieRecordPagedResponseFromJSON(json['response']),
        'errorMessage': json['errorMessage'] == null ? undefined : ErrorMessageFromJSON(json['errorMessage']),
    };
}

export function MovieRecordPagedResponseRequestResponseToJSON(json: any): MovieRecordPagedResponseRequestResponse {
    return MovieRecordPagedResponseRequestResponseToJSONTyped(json, false);
}

export function MovieRecordPagedResponseRequestResponseToJSONTyped(value?: Omit<MovieRecordPagedResponseRequestResponse, 'response'|'errorMessage'> | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
    };
}

