/* tslint:disable */
/* eslint-disable */
/**
 * CineReserve
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { GenreEnum } from './GenreEnum';
import {
    GenreEnumFromJSON,
    GenreEnumFromJSONTyped,
    GenreEnumToJSON,
    GenreEnumToJSONTyped,
} from './GenreEnum';

/**
 * 
 * @export
 * @interface MovieUpdateRecord
 */
export interface MovieUpdateRecord {
    /**
     * 
     * @type {string}
     * @memberof MovieUpdateRecord
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof MovieUpdateRecord
     */
    title?: string | null;
    /**
     * 
     * @type {string}
     * @memberof MovieUpdateRecord
     */
    description?: string | null;
    /**
     * 
     * @type {number}
     * @memberof MovieUpdateRecord
     */
    duration?: number | null;
    /**
     * 
     * @type {GenreEnum}
     * @memberof MovieUpdateRecord
     */
    genre?: GenreEnum | null;
}



/**
 * Check if a given object implements the MovieUpdateRecord interface.
 */
export function instanceOfMovieUpdateRecord(value: object): value is MovieUpdateRecord {
    if (!('id' in value) || value['id'] === undefined) return false;
    return true;
}

export function MovieUpdateRecordFromJSON(json: any): MovieUpdateRecord {
    return MovieUpdateRecordFromJSONTyped(json, false);
}

export function MovieUpdateRecordFromJSONTyped(json: any, ignoreDiscriminator: boolean): MovieUpdateRecord {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'title': json['title'] == null ? undefined : json['title'],
        'description': json['description'] == null ? undefined : json['description'],
        'duration': json['duration'] == null ? undefined : json['duration'],
        'genre': json['genre'] == null ? undefined : GenreEnumFromJSON(json['genre']),
    };
}

export function MovieUpdateRecordToJSON(json: any): MovieUpdateRecord {
    return MovieUpdateRecordToJSONTyped(json, false);
}

export function MovieUpdateRecordToJSONTyped(value?: MovieUpdateRecord | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'title': value['title'],
        'description': value['description'],
        'duration': value['duration'],
        'genre': GenreEnumToJSON(value['genre']),
    };
}

