/* tslint:disable */
/* eslint-disable */
/**
 * CineReserve
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { GenreEnum } from './GenreEnum';
import {
    GenreEnumFromJSON,
    GenreEnumFromJSONTyped,
    GenreEnumToJSON,
    GenreEnumToJSONTyped,
} from './GenreEnum';

/**
 * 
 * @export
 * @interface MovieRecord
 */
export interface MovieRecord {
    /**
     * 
     * @type {string}
     * @memberof MovieRecord
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof MovieRecord
     */
    title: string;
    /**
     * 
     * @type {string}
     * @memberof MovieRecord
     */
    description: string;
    /**
     * 
     * @type {number}
     * @memberof MovieRecord
     */
    duration: number;
    /**
     * 
     * @type {GenreEnum}
     * @memberof MovieRecord
     */
    genre: GenreEnum;
}



/**
 * Check if a given object implements the MovieRecord interface.
 */
export function instanceOfMovieRecord(value: object): value is MovieRecord {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('title' in value) || value['title'] === undefined) return false;
    if (!('description' in value) || value['description'] === undefined) return false;
    if (!('duration' in value) || value['duration'] === undefined) return false;
    if (!('genre' in value) || value['genre'] === undefined) return false;
    return true;
}

export function MovieRecordFromJSON(json: any): MovieRecord {
    return MovieRecordFromJSONTyped(json, false);
}

export function MovieRecordFromJSONTyped(json: any, ignoreDiscriminator: boolean): MovieRecord {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'title': json['title'],
        'description': json['description'],
        'duration': json['duration'],
        'genre': GenreEnumFromJSON(json['genre']),
    };
}

export function MovieRecordToJSON(json: any): MovieRecord {
    return MovieRecordToJSONTyped(json, false);
}

export function MovieRecordToJSONTyped(value?: MovieRecord | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'title': value['title'],
        'description': value['description'],
        'duration': value['duration'],
        'genre': GenreEnumToJSON(value['genre']),
    };
}

