/* tslint:disable */
/* eslint-disable */
/**
 * CineReserve
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ScreenEnum } from './ScreenEnum';
import {
    ScreenEnumFromJSON,
    ScreenEnumFromJSONTyped,
    ScreenEnumToJSON,
    ScreenEnumToJSONTyped,
} from './ScreenEnum';

/**
 * 
 * @export
 * @interface ScreeningUpdateRecord
 */
export interface ScreeningUpdateRecord {
    /**
     * 
     * @type {string}
     * @memberof ScreeningUpdateRecord
     */
    id: string;
    /**
     * 
     * @type {Date}
     * @memberof ScreeningUpdateRecord
     */
    startTime?: Date | null;
    /**
     * 
     * @type {string}
     * @memberof ScreeningUpdateRecord
     */
    movieId?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ScreeningUpdateRecord
     */
    hallId?: string | null;
    /**
     * 
     * @type {ScreenEnum}
     * @memberof ScreeningUpdateRecord
     */
    screenType?: ScreenEnum | null;
}



/**
 * Check if a given object implements the ScreeningUpdateRecord interface.
 */
export function instanceOfScreeningUpdateRecord(value: object): value is ScreeningUpdateRecord {
    if (!('id' in value) || value['id'] === undefined) return false;
    return true;
}

export function ScreeningUpdateRecordFromJSON(json: any): ScreeningUpdateRecord {
    return ScreeningUpdateRecordFromJSONTyped(json, false);
}

export function ScreeningUpdateRecordFromJSONTyped(json: any, ignoreDiscriminator: boolean): ScreeningUpdateRecord {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'startTime': json['startTime'] == null ? undefined : (new Date(json['startTime'])),
        'movieId': json['movieId'] == null ? undefined : json['movieId'],
        'hallId': json['hallId'] == null ? undefined : json['hallId'],
        'screenType': json['screenType'] == null ? undefined : ScreenEnumFromJSON(json['screenType']),
    };
}

export function ScreeningUpdateRecordToJSON(json: any): ScreeningUpdateRecord {
    return ScreeningUpdateRecordToJSONTyped(json, false);
}

export function ScreeningUpdateRecordToJSONTyped(value?: ScreeningUpdateRecord | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'startTime': value['startTime'] == null ? undefined : ((value['startTime'] as any).toISOString()),
        'movieId': value['movieId'],
        'hallId': value['hallId'],
        'screenType': ScreenEnumToJSON(value['screenType']),
    };
}

