name: CI/CD CineReserve

on:
  push:
    branches: [ "IDP" ]
  workflow_dispatch:
  

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Login to DockerHub
      run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
    - name: Build and push Auth-Service
      run: |
        docker build -t lucaplian6650/cinereserve-auth:latest ./Auth-Service
        docker push lucaplian6650/cinereserve-auth:latest
    - name: Build and push Catalog-Service
      run: |
        docker build -t lucaplian6650/cinereserve-catalog:latest ./Catalog-Service
        docker push lucaplian6650/cinereserve-catalog:latest
    - name: Build and push Booking-Service
      run: |
        docker build -t lucaplian6650/cinereserve-booking:latest ./Booking-Service
        docker push lucaplian6650/cinereserve-booking:latest
    - name: Build and push FrontEnd-Service
      run: |
        docker build -t lucaplian6650/cinereserve-frontend:latest ./FrontEnd-Service
        docker push lucaplian6650/cinereserve-frontend:latest
        
      
